language: go

go:
  - 1.11.12
  - 1.12

env:
  - GO111MODULE=on

os:
  - linux
dist: trusty

  #branches:
  #only:
  #    - master

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}
git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

    #- name: "Windows"
    #  os: windows
    #  before_install:
    #    - choco install winpcap
    #  script:
    #    - ./gonetmon

install:
  - cd app
  - go build dbmon.go

#script:
  #- go run RealTraffic/RealTraffic.go &> /dev/null & sudo ./sniffer -timeout=200
  #- sonar-scanner

after_success:
  - sonar-scanner -X